# Generated by Django 3.1.2 on 2020-10-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('modulo', models.CharField(blank=True, db_column='Nomeempresa', max_length=100, null=True)),
            ],
            options={
                'db_table': 'modulos',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='customusuario',
            name='idmodulos',
            field=models.ManyToManyField(to='core.Modulos'),
        ),
    ]
