# Generated by Django 3.1.2 on 2020-11-09 13:19

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201029_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='importacao')),
                ('tipoimportacao', models.CharField(choices=[('CO', 'CONSUMO'), ('RM', 'RATEIO MUTAVEL'), ('RI', 'RATEIO IMUTAVEL'), ('NF', 'NOTA FISCAL'), ('CE', 'CENTRO DE CUSTO'), ('CI', 'CIRURGIA')], default='CO', max_length=2, verbose_name='Tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codempresa',
            field=models.CharField(db_column='Codempresa', default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logoempresa',
            field=stdimage.models.StdImageField(upload_to='logo', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nomeempresa',
            field=models.CharField(db_column='Nomeempresa', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
