# Generated by Django 3.1.2 on 2020-11-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201109_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='criadopor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customusuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='criadopor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customusuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulos',
            name='criadopor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customusuario'),
            preserve_default=False,
        ),
    ]
