# Generated by Django 3.1.2 on 2020-11-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201109_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='idempresa',
            field=models.ForeignKey(blank=True, db_column='idempresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresa', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='idfilial',
            field=models.ForeignKey(blank=True, db_column='idfilial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filiail', to='core.filial'),
        ),
    ]
