# Generated by Django 3.1.2 on 2020-11-18 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201118_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='idempresa',
            field=models.ForeignKey(blank=True, db_column='idempresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarioempresa', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='idfilial',
            field=models.ForeignKey(blank=True, db_column='idfilial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuariofilial', to='core.filial'),
        ),
    ]
