# Generated by Django 3.1.2 on 2020-11-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20201029_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nota', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, unique=True)),
                ('inicio', models.DecimalField(decimal_places=2, max_digits=99)),
                ('fim', models.DecimalField(decimal_places=2, max_digits=99)),
                ('cor', models.CharField(choices=[('BLUE', 'AZUL'), ('GREEN', 'VERDE'), ('Gold', 'AMARELO'), ('ORANGE', 'LARANJA'), ('RED', 'VERMELHO')], default='RED', max_length=14, unique=True)),
            ],
            options={
                'db_table': 'av_nota',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PainelGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('periodo', models.CharField(max_length=6)),
                ('codigo', models.IntegerField(default='1')),
                ('descricao', models.CharField(max_length=100)),
                ('orcadometa', models.DecimalField(decimal_places=2, max_digits=18)),
                ('realizado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=18)),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=18)),
                ('idempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresaspainel', to='core.empresa')),
                ('idfilial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial', to='core.filial')),
            ],
            options={
                'db_table': 'av_painelgeral',
                'managed': True,
                'unique_together': {('idfilial', 'idempresa', 'codigo', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='DetalheIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('periodo', models.CharField(max_length=6)),
                ('descricao', models.CharField(max_length=100, unique=True)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('idempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresasdetalheindicador', to='core.empresa')),
                ('idfilial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filialdetalheindicador', to='core.filial')),
                ('idindicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicador', to='avcadastro.painelgeral')),
            ],
            options={
                'db_table': 'av_detalheindicador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotaFilial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('periodo', models.CharField(max_length=6)),
                ('nota', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('idempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresasnota', to='core.empresa')),
                ('idfilial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filialnota', to='core.filial')),
            ],
            options={
                'db_table': 'av_notafilial',
                'managed': True,
                'unique_together': {('idfilial', 'periodo')},
            },
        ),
    ]
