# Generated by Django 3.1.2 on 2020-11-09 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201109_1019'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avcadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalheindicador',
            name='criadopor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customusuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='criadopor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customusuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notafilial',
            name='criadopor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customusuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painelgeral',
            name='criadopor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customusuario'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('codigo', models.IntegerField(default='1')),
                ('descricao', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=18)),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=18)),
                ('criadopor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresaindicador', to='core.empresa')),
                ('idfilial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filialindicador', to='core.filial')),
            ],
            options={
                'db_table': 'av_indicador',
                'managed': True,
                'unique_together': {('idfilial', 'idempresa', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='painelgeral',
            name='idindicador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='painelindicador', to='avcadastro.indicador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalheindicador',
            name='idindicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicador', to='avcadastro.indicador'),
        ),
        migrations.AlterUniqueTogether(
            name='painelgeral',
            unique_together={('idfilial', 'idempresa', 'idindicador', 'periodo')},
        ),
        migrations.RemoveField(
            model_name='painelgeral',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='painelgeral',
            name='descricao',
        ),
    ]
