# Generated by Django 3.1.2 on 2020-11-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avcadastro', '0002_auto_20201109_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='pontuacao',
        ),
    ]
