# Generated by Django 3.1.2 on 2020-11-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avcadastro', '0003_remove_indicador_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalheindicador',
            name='incluso',
            field=models.BooleanField(default=True, verbose_name='Incluso no Calculo?'),
        ),
        migrations.AddField(
            model_name='detalheindicador',
            name='modoindicador',
            field=models.CharField(choices=[('CSM', 'CALCULO SOMA'), ('CSB', 'CALCULO SUBTRAI'), ('CMU', 'CALCULO MULTIPLICA'), ('CDI', 'CALCULO DIVIDE'), ('UNI', 'UNITARIO'), ('CON', 'CONTAR')], default='CSM', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='modo',
            field=models.CharField(choices=[('CAL', 'CALCULO'), ('CON', 'CONTAR'), ('UNI', 'UNITARIO')], default='CAL', max_length=3),
            preserve_default=False,
        ),
    ]
