# Generated by Django 3.1.2 on 2020-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avcadastro', '0004_auto_20201109_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalheindicador',
            name='Inverso',
            field=models.BooleanField(default=False, verbose_name='Incluso no Calculo?'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='Inverso',
            field=models.BooleanField(default=False, verbose_name='Incluso no Calculo?'),
        ),
    ]
