# Generated by Django 3.1.2 on 2020-11-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avcadastro', '0005_auto_20201109_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalheindicador',
            name='Inverso',
            field=models.BooleanField(default=False, verbose_name='Calculo Inverso?'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='Inverso',
            field=models.BooleanField(default=False, verbose_name='Calculo Inverso?'),
        ),
    ]
