# Generated by Django 3.1.2 on 2020-11-18 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20201118_1904'),
        ('avcadastro', '0007_auto_20201109_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalheindicador',
            name='criadopor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalheindicador',
            name='idempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresasdetalheindicador', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='detalheindicador',
            name='idfilial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filialdetalheindicador', to='core.filial'),
        ),
        migrations.AlterField(
            model_name='detalheindicador',
            name='idindicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='indicador', to='avcadastro.indicador'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='criadopor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='idempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresaindicador', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='idfilial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filialindicador', to='core.filial'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='criadopor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notafilial',
            name='criadopor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notafilial',
            name='idempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresasnota', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='notafilial',
            name='idfilial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filialnota', to='core.filial'),
        ),
        migrations.AlterField(
            model_name='painelgeral',
            name='criadopor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='painelgeral',
            name='idempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresaspainel', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='painelgeral',
            name='idfilial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filial', to='core.filial'),
        ),
        migrations.AlterField(
            model_name='painelgeral',
            name='idindicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='painelindicador', to='avcadastro.indicador'),
        ),
    ]
