# Generated by Django 3.1.2 on 2020-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201118_1928'),
        ('avcadastro', '0008_auto_20201118_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalheindicador',
            options={'managed': True, 'ordering': ['periodo', 'idindicador']},
        ),
        migrations.AlterField(
            model_name='detalheindicador',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='notafilial',
            unique_together={('idfilial', 'periodo', 'idempresa')},
        ),
    ]
